college_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("", include('main_app.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path

from main_app.EditResultView import EditResultView

from . import hod_views, staff_views, student_views, views


urlpatterns = [
    path("", views.login_page, name='login_page'),
    path("get_attendance", views.get_attendance, name='get_attendance'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin/home/", hod_views.admin_home, name='admin_home'),
    path("staff/add", hod_views.add_staff, name='add_staff'),
    path("department/add", hod_views.add_department, name='add_department'),
    path("major/add", hod_views.add_major, name='add_major'),
    path("grade/add", hod_views.add_grade, name='add_grade'),
    path("room/add", hod_views.add_room, name='add_room'),
    path("send_student_notification/", hod_views.send_student_notification,
         name='send_student_notification'),
    path("send_staff_notification/", hod_views.send_staff_notification,
         name='send_staff_notification'),
    path("add_session/", hod_views.add_session, name='add_session'),
    path("admin_notify_student", hod_views.admin_notify_student,
         name='admin_notify_student'),
    path("admin_notify_staff", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
    path("admin_view_profile", hod_views.admin_view_profile,
         name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("session/manage/", hod_views.manage_session, name='manage_session'),
    path("session/edit/<int:session_id>",
         hod_views.edit_session, name='edit_session'),
    path("student/view/feedback/", hod_views.student_feedback_message,
         name="student_feedback_message",),
    path("staff/view/feedback/", hod_views.staff_feedback_message,
         name="staff_feedback_message",),
    path("student/view/leave/", hod_views.view_student_leave,
         name="view_student_leave",),
    path("staff/view/leave/", hod_views.view_staff_leave, name="view_staff_leave",),
    path("attendance/view/", hod_views.admin_view_attendance,
         name="admin_view_attendance",),
    path("attendance/fetch/", hod_views.get_admin_attendance,
         name='get_admin_attendance'),
    path("student/add/", hod_views.add_student, name='add_student'),
    path("subject/add/", hod_views.add_subject, name='add_subject'),
    path("staff/manage/", hod_views.manage_staff, name='manage_staff'),
    path("student/manage/", hod_views.manage_student, name='manage_student'),
    path("department/manage/", hod_views.manage_department, name='manage_department'),
    path("major/manage/", hod_views.manage_major, name='manage_major'),
    path("grade/manage/", hod_views.manage_grade, name='manage_grade'),
    path("grade/list/<grade_id>", hod_views.list_student, name='list_student'),
    path("subject/manage/", hod_views.manage_subject, name='manage_subject'),
    path("room/manage/", hod_views.manage_room, name='manage_room'),

    path("staff/edit/<admin_id>",
         hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<admin_id>",
         hod_views.delete_staff, name='delete_staff'),

    path("student/delete/<admin_id>",
         hod_views.delete_student, name='delete_student'),
    path("student/edit/<admin_id>",
         hod_views.edit_student, name='edit_student'),

    path("department/delete/<department_id>",
         hod_views.delete_department, name='delete_department'),

    path("major/delete/<major_id>",
         hod_views.delete_major, name='delete_major'),

    path("grade/delete/<grade_id>",
         hod_views.delete_grade, name='delete_grade'),

    path("subject/delete/<subject_id>",
         hod_views.delete_subject, name='delete_subject'),

    path("room/delete/<room_id>",
         hod_views.delete_room, name='delete_room'),

    path("session/delete/<session_id>",
         hod_views.delete_session, name='delete_session'),

    path("department/edit/<department_id>",
         hod_views.edit_department, name='edit_department'),
    path("major/edit/<major_id>",
         hod_views.edit_major, name='edit_major'),
    path("grade/edit/<grade_id>",
         hod_views.edit_grade, name='edit_grade'),
    path("subject/edit/<subject_id>",
         hod_views.edit_subject, name='edit_subject'),
    path("room/edit/<room_id>",
         hod_views.edit_room, name='edit_room'),

    path("upload/csv/student", hod_views.upload_file_view, name='upload_view'),
    path("upload/csv/staff", hod_views.upload_file_staff, name='upload_staff'),
    path("upload/csv/sub", hod_views.upload_file_view_sub, name='upload_sub'),


    #Asign
    path("assign/manage/", hod_views.manage_assign, name='manage_assign'),
    path("assign/delete/<assign_id>", hod_views.delete_assign, name='delete_assign'),
    path('assign/add/', hod_views.add_assign, name='add_assign'),
    path('assign/edit/<assign_id>/', hod_views.edit_assign, name='edit_assign'),


    # Staff
    path("staff/home/", staff_views.staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_views.staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/feedback/", staff_views.staff_feedback, name='staff_feedback'),
    path("staff/view/profile/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/attendance/take/", staff_views.staff_take_attendance,
         name='staff_take_attendance'),
    path("staff/attendance/update/", staff_views.staff_update_attendance,
         name='staff_update_attendance'),
    path("staff/get_students/", staff_views.get_students, name='get_students'),
    path("staff/attendance/fetch/", staff_views.get_student_attendance,
         name='get_student_attendance'),
    path("staff/attendance/save/",
         staff_views.save_attendance, name='save_attendance'),
    path("staff/attendance/update/",
         staff_views.update_attendance, name='update_attendance'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", staff_views.staff_view_notification,
         name="staff_view_notification"),
    path("staff/result/add/", staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/", EditResultView.as_view(),
         name='edit_student_result'),
    path('staff/result/fetch/', staff_views.fetch_student_result,
         name='fetch_student_result'),



    # Student
    path("student/home/", student_views.student_home, name='student_home'),
    path("student/view/attendance/", student_views.student_view_attendance,
         name='student_view_attendance'),
    path("student/apply/leave/", student_views.student_apply_leave,
         name='student_apply_leave'),
    path("student/feedback/", student_views.student_feedback,
         name='student_feedback'),
    path("student/view/profile/", student_views.student_view_profile,
         name='student_view_profile'),
    path("student/fcmtoken/", student_views.student_fcmtoken,
         name='student_fcmtoken'),
    path("student/view/notification/", student_views.student_view_notification,
         name="student_view_notification"),
    path('student/view/result/', student_views.student_view_result,
         name='student_view_result'),
    path('student/view/fee/', student_views.student_view_fee,
         name='student_view_fee'),

]

main_app/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import UserManager
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import AbstractUser


subject_choice = (
    (0, '0'),
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
)

time_slots = (
    ('1 - 2', '1 - 2'),
    ('1 - 3', '1 - 3'),
    ('1 - 4', '1 - 4'),
    ('1 - 5', '1 - 5'),
    ('2 - 3', '2 - 3'),
    ('2 - 4', '2 - 4'),
    ('2 - 5', '2 - 5'),
    ('3 - 4', '3 - 4'),
    ('3 - 5', '3 - 5'),
    ('4 - 5', '4 - 5'),
    ('6 - 7', '6 - 7'),
    ('6 - 8', '6 - 8'),
)

DAYS_OF_WEEK = (
    ('Thứ Hai', 'Thứ Hai'),
    ('Thứ Ba', 'Thứ Ba'),
    ('Thứ Tư', 'Thứ Tư'),
    ('Thứ Năm', 'Thứ Năm'),
    ('Thứ Sáu', 'Thứ Sáu'),
    ('Thứ Bảy', 'Thứ Bảy'),
)

gender_choice = (
    ('Nam', 'Nam'),
    ('Nữ', 'Nữ')
)

level_choice = (
    ('Giáo sư', 'Giáo sư'),
    ('Phó giáo sư', 'Phó giáo sư'),
    ('Tiến sĩ', 'Tiến sĩ'),
    ('Thạc sĩ', 'Thạc sĩ'),
    ('Đại học', 'Đại học')
)


class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = CustomUser(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        assert extra_fields["is_staff"]
        assert extra_fields["is_superuser"]
        return self._create_user(email, password, **extra_fields)


class Session(models.Model):
    name = models.CharField(max_length=15)
    year = models.CharField(max_length=20)

    def __str__(self):
        return self.name + " (" + self.year + ")"


class Room(models.Model):
    name = models.CharField(max_length=20)
    dimension = models.IntegerField()

    def __str__(self):
        return self.name


class CustomUser(AbstractUser):
    USER_TYPE = ((1, "PDT"), (2, "GV"), (3, "SV"))
    id = models.CharField(primary_key='True', max_length=10)
    username = None  # Removed username, using email instead
    email = models.EmailField(unique=True)
    user_type = models.CharField(default=1, choices=USER_TYPE, max_length=1)
    fcm_token = models.TextField(default="")  # For firebase notifications

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = CustomUserManager()


class Admin(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True, blank=True)


class Department(models.Model):
    id = models.CharField(primary_key='True', max_length=50)
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Major(models.Model):
    id = models.CharField(primary_key='True', max_length=50)
    name = models.CharField(max_length=120)
    department = models.ForeignKey(Department, on_delete=models.DO_NOTHING, null=True, blank=False)

    def __str__(self):
        return self.name


class Grade(models.Model):
    id = models.CharField(primary_key='True', max_length=50)
    name = models.CharField(max_length=120)
    course = models.IntegerField(max_length=5)
    major = models.ForeignKey(Major, on_delete=models.DO_NOTHING, null=True, blank=False)

    def __str__(self):
        return self.name


class Student(models.Model):
    admin = models.OneToOneField(CustomUser, primary_key='True', on_delete=models.CASCADE, blank=False)
    last_name = models.CharField(max_length=200)
    first_name = models.CharField(max_length=200)
    profile_pic = models.ImageField(null=True, blank=True, upload_to='images/')
    gender = models.CharField(max_length=3, choices=gender_choice)
    dob = models.DateField(null=True)
    pob = models.CharField(max_length=200, null=True)
    grade = models.ForeignKey(Grade, on_delete=models.DO_NOTHING, null=True, blank=False)
    number = models.CharField(max_length=15, null=True)
    address = models.TextField(null=True)
    major = models.ForeignKey(Major, on_delete=models.DO_NOTHING, null=True, blank=False)

    def __str__(self):
        return '%s: %s' % (self.admin_id, self.last_name + " " + self.first_name)


class Staff(models.Model):
    admin = models.OneToOneField(CustomUser, primary_key='True', on_delete=models.CASCADE, blank=False)
    last_name = models.CharField(max_length=200)
    first_name = models.CharField(max_length=200)
    profile_pic = models.ImageField(null=True, blank=True, upload_to="images/")
    gender = models.CharField(max_length=3, choices=gender_choice)
    dob = models.DateField(null=True)
    pob = models.CharField(max_length=200, null=True)
    level = models.CharField(max_length=30, choices=level_choice)
    number = models.CharField(max_length=15, null=True)
    address = models.TextField(null=True)
    major = models.ForeignKey(Major, on_delete=models.DO_NOTHING, null=True, blank=False)
    department = models.ForeignKey(Department, on_delete=models.DO_NOTHING, null=True, blank=False)

    def __str__(self):
        return '%s: %s' % (self.admin_id, self.last_name + " " + self.first_name)


class Subject(models.Model):
    id = models.CharField(primary_key='True', max_length=50)
    name = models.CharField(max_length=120)
    credit = models.IntegerField(max_length=2)
    type = models.IntegerField(choices=subject_choice, max_length=2, null=True)
    fee = models.CharField(max_length=50, null=True)
    major = models.ForeignKey(Major, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)

    # def save(self, *args, **kwargs):
    #     price = None
    #     if int(self.type) == 0:
    #         price = 0
    #     elif int(self.type) == 1:
    #         price = 280000
    #     elif int(self.type) == 2:
    #         price = 332000
    #     elif int(self.type) == 3:
    #         price = 616000
    #     elif int(self.type) == 4:
    #         price = 730000
    #     else:
    #         pass
    #     self.fee = price * self.credit
    #     super().save(*args, **kwargs)
    #
    def __str__(self):
        return '%s: %s' % (self.id, self.name)


class Assign(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True)
    group = models.CharField(max_length=5)
    period = models.CharField(max_length=50, choices=time_slots, null=True)
    day = models.CharField(max_length=15, choices=DAYS_OF_WEEK, null=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE, null=True)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.subject.name

    # def __str__(self):
    #     grade = Grade.objects.get(id=self.grade_id)
    #     sbj = Subject.objects.get(id=self.subject_id)
    #     staff = Staff.objects.get(id=self.staff_id)
    #     return '%s : %s : %s' % (sbj.name, grade.name, staff.last_name + " " + staff.first_name)


class Attendance(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.DO_NOTHING, null=True)
    session = models.ForeignKey(Session, on_delete=models.DO_NOTHING, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class AttendanceReport(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    attendance = models.ForeignKey(Attendance, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class LeaveReportStudent(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date = models.DateField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class LeaveReportStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    date = models.DateField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeedbackStudent(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeedbackStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class NotificationStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class NotificationStudent(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class StudentResult(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

main_app/templates/staff_template/edit_student_result.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                    <form method="POST">
                        {% csrf_token %}
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

       
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">


                     

                 {{ form }}

                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" id='update_result' class="btn btn-primary btn-block">Cập nhật</button>
               
                    </div>
                </div>
                </form>
            </div>
            </div>
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block custom_js %}
<script>
    $(document).ready(function () {
        $("#id_subject").change(function () {
            fetchStudents();
            });
            $("#id_session_year").change(function () {
                fetchStudents();
                });
   $("#id_student").change(function () {
    fetch_student_result();
                });
                $("#id_exam").hide()
                $("#update_result").hide()
                $('label[for="id_exam"]').hide();
        function fetchStudents(){
            var subject = $("#id_subject").val()
            var session = $("#id_session_year").val()
            $("#id_student").html(null)
            if (session.length  == 0 || subject.length == 0 || session < 1 || subject < 1){
                return false;
            }
            $.ajax({
                url: "{% url 'get_students' %}",
                type: 'POST',
                data: {
                    subject: subject,
                    session: session
                }
            }).done(function (response) {
                var json_data = JSON.parse(response)
                if (json_data.length < 1) {
                    alert("Không có dữ liệu")
                } else {
                    var div_data = "<option>Chọn sinh viên</option>"

                    for (key in json_data) {
                        div_data += "<option value='" + json_data[key]['id'] + "'>"+ json_data[key]['id'] + ": " + json_data[key]['name'] + " </option>"
                    }
             
                    $("#id_student").html(div_data)
                }
            }).fail(function (response) {
                alert("Lỗi khi tìm sinh viên")
            })
               }

               function fetch_student_result(){
                var student = $("#id_student").val()
                var subject = $("#id_subject").val()
                $("#id_exam").val(null)
                $("#id_exam").hide()
                $("#update_result").hide()
                $('label[for="id_exam"]').hide();
                if (student.length  == 0 || subject.length == 0 || student < 1 || subject < 1){
                    return false;
                }
                $.ajax({
                    url: "{% url 'fetch_student_result' %}",
                    type: 'POST',
                    data: {
                        subject: subject,
                        student: student
                    }
                }).done(function (response) {
                    if (response == 'False') {
                        alert("Không có dữ liệu")
                    } else {
                        var json_data = JSON.parse(response)
                            $("#id_exam").val(json_data['exam'])
                            $("#id_exam").show()
                            $("#update_result").show()
                            $('label[for="id_exam"]').show();

                    }
                }).fail(function (response) {
                    alert("Lỗi khi tìm sinh viên")
                })
               }

    })
</script>
{% endblock custom_js %}

main_app/templates/staff_template/staff_add_result.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                    <form method="POST">
                        {% csrf_token %}
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

       
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">


                        <div class="form-group">
                            <label>Học phần</label>
                            <select name="subject" class="form-control" id='subject'>
                                <option value="">----</option>
                                {% for subject in subjects  %}
                                <option value="{{subject.subject.id}}">{{subject.subject.id}} {{subject.subject.name}}</option>
                                {% endfor %}
                            </select>
                        </div>


                        <div class="form-group">
                            <label>Học kỳ/Năm học</label>
                            <select name="session" id='session' class="form-control">
                                <option value="">----</option>
                                {% for session in sessions  %}
                                <option value="{{session.id}}">{{session}}</option>
                                {% endfor %}
                            </select>
                        </div>


                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="button" id='fetch_student' class="btn btn-primary btn-block">Tìm</button>
                        <div class="form-group" id="student_data">

                        </div>
                    </div>
                </div>
                </form>
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block custom_js %}
<script>
    $(document).ready(function () {

       
        $("#fetch_student").click(function () {
            var subject = $("#subject").val()
            var session = $("#session").val()
            $("#student_data").html(null)
if (subject.length  == 0 || session.length == 0){
    alert("Vui lòng chọn môn học và học kỳ");
    return false;
}
            $.ajax({
                url: "{% url 'get_students' %}",
                type: 'POST',
                data: {
                    subject: subject,
                    session: session
                }
            }).done(function (response) {
                var json_data = JSON.parse(response)
                if (json_data.length < 1) {
                    alert("Không có dữ liệu")
                } else {
                    var div_data = "<hr/><div class='form-group'> <label> Danh sách sinh viên</label> <select class='student_list form-control' name='student_list'> "

                    for (key in json_data) {
                        div_data += "<option value='" + json_data[key]['id'] + "'>" + json_data[key]['id']+ ": " + json_data[key]['name'] + " </option>"
                    }
                    div_data += "</select></div>"
                    div_data += "<div class='form-group row'><div class='col-md-6'><label> Điểm số </label>  <input class='form-control' placeholder='Điểm số'  name='exam' max='10' min='0' required type='number' step='any'  /> </div></div><div class='form-group'><button id='save_attendance' class='btn btn-success' type='submit'>Lưu</button></div></div>"
                    $("#student_data").html(div_data)
                }
            }).fail(function (response) {
                alert("Không tìm thấy dữ liệu")
            })




        })
    })
</script>
{% endblock custom_js %}

main_app/templates/staff_template/staff_apply_leave.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Gửi"%}
                </div>
                <!-- /.card -->

<div class="card card-dark">
    <div class="card-header"><h3 class="card-title">Lịch sử nghỉ phép</h3></div>
   <div class="table p-2">

       <table class="table table-bordered">
           <thead class="text-center">
            <tr>
                <th>STT</th>
                <th>Ngày</th>
                <th>Nội dung</th>
             <th>Trạng thái</th>
         </tr>
           </thead>
        {% for leave in leave_history %}
        <tr>
            <td class="text-center">{{forloop.counter}}</td>
            <td>{{leave.date|date:"d/m/Y"}}</td>
              <td>{{leave.message}}</td>
              <td class="text-center">
                  
                  {% if leave.status == 0 %}
                  <span class="badge badge-warning">Đang duyệt</span>
                  {% elif leave.status == 1 %}
                  <span class="badge badge-success">Chấp nhận</span>
                    {% else %}
                    <span class="badge badge-danger">Từ chối</span>
                    {% endif %}
                    
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
            </div>
        </div>
    </div>
     </div>
</section>
{% endblock content %}

main_app/templates/staff_template/staff_feedback.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Gửi"%}
                </div>
                <!-- /.card -->
<div class="card card-dark">
    <div class="card-header"><h3 class="card-title">{{page_title}}</h3>
    </div>
   <div class="table p-2">

       <table class="table table-bordered">
       <thead class="text-center">
           <tr>
               <th>STT</th>
               <th>Nội dung đánh giá</th>
               <th>Nội dung phản hồi</th>
            <th>Thời gian</th>
        </tr>
           </thead>
        {% for feedback in feedbacks %}
        <tr>
            <td class="text-center">{{forloop.counter}}</td>
            <td>{{feedback.feedback}}</td>
              <td>
                  
                  {% if feedback.reply == "" %}
                      <p class="badge badge-warning">Đang đợi phản hồi</p>
                      {% else %}
                      {{feedback.reply}}
                  {% endif %}
                      
              </td>
              <td>{{feedback.created_at|date:"d/m/Y H:i"}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/staff_template/staff_view_notification.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>


                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">



                       


                        <div class="form-group table">
              <table class="table table-bordered">
              <thead class="text-center">
                  <tr>
                      <th class="col-1">STT</th>
                      <th>Thời gian</th>
                      <th>Thông báo</th>
                  </tr>
                  </thead>
                  {% for notification in  notifications %}
                    <tr>
                        <td class="text-center">{{forloop.counter}}</td>
                        <td>{{notification.created_at|date:"d/m/Y, H:i"}}</td>
                        <td>{{notification.message}}</td>
                    </tr>
                  {% endfor %}
              </table>
                        </div>
                   
                    </div>
    
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}